# Generated by Django 5.1.4 on 2024-12-15 23:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preparation_time', models.IntegerField()),
                ('available', models.BooleanField()),
                ('category', models.CharField(choices=[('APPETIZER', 'Appetizer'), ('MAIN_COURSE', 'Main Course'), ('DESSERT', 'Dessert'), ('BEVERAGE', 'Beverage')], max_length=20)),
                ('image_url', models.CharField(max_length=255)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Elemento del menú',
                'verbose_name_plural': 'Elementos del menú',
                'db_table': 'menu_items',
                'ordering': ['category', 'name'],
            },
        ),
    ]
