# Generated by Django 4.2 on 2024-12-16 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_total_amount"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="orderitem",
            table=None,
        ),
    ]
